version: '3.8'

services:
  # Verifier backend DB
  postgres:
    image: postgres:15
    container_name: verifier_postgres
    environment:
      POSTGRES_DB: verifier_db
      POSTGRES_USER: verifier_user
      POSTGRES_PASSWORD: verifier_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Keycloak DB
  keycloak_db:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: 21ee-109-166-139-176.ngrok-free.app
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HTTPS_PORT: 443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - keycloak_db
    restart: unless-stopped

  # Unleash DB
  unleash_db:
    image: postgres:13
    container_name: unleash_postgres
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash_pass
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Unleash Server
  unleash:
    image: unleashorg/unleash-server
    container_name: unleash
    ports:
      - "4242:4242"
    environment:
      DATABASE_HOST: unleash_db
      DATABASE_NAME: unleash
      DATABASE_USERNAME: unleash_user
      DATABASE_PASSWORD: unleash_pass
      DATABASE_SSL: "false"
      INIT_FRONTEND_API_TOKENS: default:development.unleash-insecure-api-token
      LOG_LEVEL: info
    depends_on:
      - unleash_db
    restart: unless-stopped

volumes:
  pgdata:
  keycloak_pgdata:
