services:
  # Database for your Verifier backend
  postgres:
    image: postgres:15
    container_name: verifier_postgres
    environment:
      POSTGRES_DB: verifier_db
      POSTGRES_USER: verifier_user
      POSTGRES_PASSWORD: verifier_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # PostgreSQL for Keycloak
  keycloak_db:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Keycloak Server (Quarkus distribution)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: e9b5-109-166-132-30.ngrok-free.app
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HTTPS_PORT: 443
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - keycloak_db
    restart: unless-stopped

volumes:
  pgdata:
  keycloak_pgdata:
