version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: verifier_postgres
    environment:
      POSTGRES_DB: verifier_db
      POSTGRES_USER: verifier_user
      POSTGRES_PASSWORD: verifier_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
